apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: protonmail-bridge-pv-claim
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi