apiVersion: apps/v1
kind: Deployment
metadata:
  name: protonmail-bridge-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: protonmail-bridge
  template:
    metadata:
      labels:
        app: protonmail-bridge
    spec:
      volumes: 
        - name: protonmail-data
          persistentVolumeClaim: 
            claimName: protonmail-bridge-pv-claim
      containers:
      - name: protonmail-bridge-container
        volumeMounts:
          - mountPath: "/root/"
            name: protonmail-data
        image: shenxn/protonmail-bridge:1.8.10-build
        ports:
        - containerPort: 25
---
apiVersion: v1
kind: Service
metadata:
  name: smtp-service
spec:
  type: NodePort
  selector:
    app: protonmail-bridge
  ports:
    - port: 25